version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk-network
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.3
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - "../logstash-ingest-data/:/usr/share/logstash/ingest_data/"
      - "../logstash-config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    restart: always
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk-network
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=toor12345678
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data
    restart: always
    networks:
      - elk-network

networks:
  elk-network:
    name: elk-network

volumes:
  minio-data: